---
# tasks file for nginx-wordpress
- name: "install nginx for wordpress"
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: "create folder wordpress"
  become: true
  ansible.builtin.file:
    path: /var/www/wordpress/html
    state: directory
    mode: "0644"
- name: "create file wordpress"
  become: true
  template:
    src: wordpress.j2
    dest: /etc/nginx/sites-available/default
    mode: "0644"

- name: restart nginx wordpress
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

