---
# tasks file for php
- name: "install php"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - php-cli
    - php-fpm
    - php-mysql
    - php-json
    - php-curl
    - php-gd
    - php-intl
    - php-mbstring
    - php-soap
    - php-xml
    - php-xmlrpc
    - php-zip
- name: restart php-fpm
  become: true
  ansible.builtin.service:
    name: php7.2-fpm
    state: restarted
