---
- name: Install_Nginx
  hosts: nginx-1
  roles:
    - squid
    - nginx_letsencrypt

#############
### mysql
#################
- name: install mysql
  hosts: mysql
  gather_facts: false
  pre_tasks:
    - name: copy proxy congig file
      become: true
      ansible.builtin.copy:
        src: files/proxy.conf
        dest: /etc/apt/apt.conf.d/proxy.conf
        mode: "0644"
  roles:
    - mysql-install
    - master_slave
  environment:
    http_proxy: http://{{ ip_nginx }}:3128
    https_proxy: http://{{ ip_nginx }}:3128


##############
###   wordpress
#################
- name: "Install_wordpress"
  hosts: wordpress
  gather_facts: false
  pre_tasks:
    - name: "copy proxy config file to wordpress"
      become: true
      ansible.builtin.copy:
        src: files/proxy.conf
        dest: /etc/apt/apt.conf.d/proxy.conf
        mode: "0644"
  roles:
    - php
    - nginx-wordpress
    - wordpress
    - wordpress_config
  environment:
    http_proxy: http://{{ ip_nginx }}:3128
    https_proxy: http://{{ ip_nginx }}:3128
  tags:
    - config_wp

###############
### node_exporter
###############
- name: "install node_exporter"
  hosts:
    - monitoring
    - mysql
    - wordpress
    - gitlabrunner
  gather_facts: false
  roles:
    - install_node_exporter
  environment:
    http_proxy: http://{{ ip_nginx }}:3128
    https_proxy: http://{{ ip_nginx }}:3128
  tags:
    - config_node_exporter
- name: "install node_exporter to nginx server"
  hosts:
    - nginx-1
  gather_facts: false
  roles:
    - install_node_exporter
  tags:
    - config_node_exporter

####################
### prometheus
####################
- name: "Install_prometeus"
  hosts: monitoring
  gather_facts: false
  pre_tasks:
    - name: "copy proxy config file to wordpress"
      become: true
      ansible.builtin.copy:
        src: files/proxy.conf
        dest: /etc/apt/apt.conf.d/proxy.conf
        mode: "0644"
  roles:
    - install_prometheus
    - install_node_exporter
    - install_alertmanager
    - install_grafana
  environment:
    http_proxy: http://{{ ip_nginx }}:3128
    https_proxy: http://{{ ip_nginx }}:3128
  tags:
    - config_prometeus
####################
### gitlab
####################
- name: "Install_gitlab"
  hosts:
    - gitlabrunner
    - wordpress
  pre_tasks:
    - name: "copy proxy config file to wordpress"
      become: true
      ansible.builtin.copy:
        src: files/proxy.conf
        dest: /etc/apt/apt.conf.d/proxy.conf
        mode: "0644"
    - name: "gitlab to hosts gitlab-runner"
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ip_nginx }} {{ domain_gitlab }}"
      when:
        - inventory_hostname == 'runner'
    - name: "disable GIT_SSL_NO_VERIFY gitlab-runner"
      become: true
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "GIT_SSL_NO_VERIFY=true"
      when:
        - inventory_hostname == 'runner'

  roles:
    - install_gitlab
  environment:
    http_proxy: http://{{ ip_nginx }}:3128
    https_proxy: http://{{ ip_nginx }}:3128
  tags:
    - config_gitlab_ce

